site_name: AWS Lambda Powertools Python
nav:
  - Homepage: index.md
  - Core utilities:
      - core/tracer.md
      - core/logger.md
      - core/metrics.md
  - Utilities:
      - utilities/middleware_factory.md
      - utilities/parameters.md
      - utilities/batch.md
      - utilities/typing.md
      - utilities/validation.md
      - utilities/data_classes.md
      - utilities/parser.md

theme:
  name: material
  palette:
    primary: deep purple
  features:
    - navigation.sections
  icon:
    repo: fontawesome/brands/github
  logo: media/aws-logo-light.svg

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - meta


repo_url: https://github.com/awslabs/aws-lambda-powertools-python
